In [26]:
import pandas as pd
import numpy as np

In [27]:
df = pd.read_csv('OSX_DS_assignment.csv')

In [28]:
df_trail = df.filter(['review_description','price','winery','variety'], axis=1)
df_trail.head(10)

,review_description,price,winery,variety
0,"Aromas include tropical fruit, broom, brimston...",NaN,Nicosia,White Blend
1,"This is ripe and fruity, a wine that is smooth...",15.0,Quinta dos Avidagos,Portuguese Red
2,"Tart and snappy, the flavors of lime flesh and...",14.0,Rainstorm,Pinot Gris
3,"Pineapple rind, lemon pith and orange blossom ...",13.0,St. Julian,Riesling
4,"Much like the regular bottling from 2012, this...",65.0,Sweet Cheeks,Pinot Noir
5,This dry and restrained wine offers spice in p...,24.0,Trimbach,Gewürztraminer
6,Savory dried thyme notes accent sunnier flavor...,12.0,Heinz Eifel,Gewürztraminer
7,This has great depth of flavor with its fresh ...,27.0,Jean-Baptiste Adam,Pinot Gris
8,"Soft, supple plum envelopes an oaky structure ...",19.0,Kirkland Signature,Cabernet Sauvignon
9,"This is a dry wine, very spicy, with a tight, ...",30.0,Leon Beyer,Gewürztraminer

In [29]:
df_trail.isnull().sum()

review_description       0
price                 6963
winery                   0
variety                  0
dtype: int64

In [30]:
print(df_trail['winery'].value_counts())
print(df_trail['variety'].value_counts())

Testarossa               217
Williams Selyem          203
Louis Latour             199
Georges Duboeuf          195
Chateau Ste. Michelle    187
                        ...
Vignobles de Roany         1
Werewolf                   1
Beautiful Dream            1
Ankida Ridge               1
Penedo Borges              1
Name: winery, Length: 14728, dtype: int64
Pinot Noir                    13272
Chardonnay                    11753
Cabernet Sauvignon             9472
Red Blend                      8946
Bordeaux-style Red Blend       6915
Riesling                       5189
Sauvignon Blanc                4967
Syrah                          4142
Rosé                           3564
Merlot                         3102
Nebbiolo                       2804
Zinfandel                      2714
Sangiovese                     2707
Malbec                         2652
Portuguese Red                 2466
White Blend                    2360
Sparkling Blend                2153
Tempranillo                    1810
Rhône-style Red Blend          1471
Pinot Gris                     1455
Champagne Blend                1396
Cabernet Franc                 1353
Grüner Veltliner               1345
Portuguese White               1159
Bordeaux-style White Blend     1066
Pinot Grigio                   1052
Gamay                          1025
Gewürztraminer                 1012
Name: variety, dtype: int64

In [31]:
df_trail = df_trail[df_trail['price'].notna()]
df_trail.head(10)

,review_description,price,winery,variety
1,"This is ripe and fruity, a wine that is smooth...",15.0,Quinta dos Avidagos,Portuguese Red
2,"Tart and snappy, the flavors of lime flesh and...",14.0,Rainstorm,Pinot Gris
3,"Pineapple rind, lemon pith and orange blossom ...",13.0,St. Julian,Riesling
4,"Much like the regular bottling from 2012, this...",65.0,Sweet Cheeks,Pinot Noir
5,This dry and restrained wine offers spice in p...,24.0,Trimbach,Gewürztraminer
6,Savory dried thyme notes accent sunnier flavor...,12.0,Heinz Eifel,Gewürztraminer
7,This has great depth of flavor with its fresh ...,27.0,Jean-Baptiste Adam,Pinot Gris
8,"Soft, supple plum envelopes an oaky structure ...",19.0,Kirkland Signature,Cabernet Sauvignon
9,"This is a dry wine, very spicy, with a tight, ...",30.0,Leon Beyer,Gewürztraminer
10,"Slightly reduced, this wine offers a chalky, t...",34.0,Louis M. Martini,Cabernet Sauvignon

In [32]:
# df_trail.describe()
df_trail['price'].isna().sum()

0

In [33]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer
from nltk.tokenize import word_tokenize

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def preprocess_text(text):
    tokens = word_tokenize(text.lower())  # Tokenize the text
    filtered_tokens = [lemmatizer.lemmatize(token) for token in tokens if token.isalpha() and token not in stop_words]
    return ' '.join(filtered_tokens)

df_trail['review_description'] = df_trail['review_description'].apply(preprocess_text)

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\Lenovo\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

In [34]:
print(df_trail.head(10))

                                   review_description  price  \
1   ripe fruity wine smooth still structured firm ...   15.0
2   tart snappy flavor lime flesh rind dominate gr...   14.0
3   pineapple rind lemon pith orange blossom start...   13.0
4   much like regular bottling come across rather ...   65.0
5   dry restrained wine offer spice profusion bala...   24.0
6   savory dried thyme note accent sunnier flavor ...   12.0
7   great depth flavor fresh apple pear fruit touc...   27.0
8   soft supple plum envelope oaky structure caber...   19.0
9   dry wine spicy tight taut texture strongly min...   30.0
10  slightly reduced wine offer chalky tannic back...   34.0

                 winery             variety
1   Quinta dos Avidagos      Portuguese Red
2             Rainstorm          Pinot Gris
3            St. Julian            Riesling
4          Sweet Cheeks          Pinot Noir
5              Trimbach      Gewürztraminer
6           Heinz Eifel      Gewürztraminer
7    Jean-Baptiste Adam          Pinot Gris
8    Kirkland Signature  Cabernet Sauvignon
9            Leon Beyer      Gewürztraminer
10     Louis M. Martini  Cabernet Sauvignon

In [35]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df_trail['variety_encoded'] = le.fit_transform(df_trail['variety'])
df_trail

,review_description,price,winery,variety,variety_encoded
1,ripe fruity wine smooth still structured firm ...,15.0,Quinta dos Avidagos,Portuguese Red,15
2,tart snappy flavor lime flesh rind dominate gr...,14.0,Rainstorm,Pinot Gris,13
3,pineapple rind lemon pith orange blossom start...,13.0,St. Julian,Riesling,19
4,much like regular bottling come across rather ...,65.0,Sweet Cheeks,Pinot Noir,14
5,dry restrained wine offer spice profusion bala...,24.0,Trimbach,Gewürztraminer,7
...,...,...,...,...,...
103317,note honeysuckle cantaloupe sweeten deliciousl...,28.0,Dr. H. Thanisch (Erben Müller-Burggraef),Riesling,19
103318,citation given much decade bottle age prior re...,75.0,Citation,Pinot Noir,14
103319,gravel soil give wine crisp dry character ripe...,30.0,Domaine Gresser,Gewürztraminer,7
103320,dry style pinot gris crisp acidity also weight...,32.0,Domaine Marcel Deiss,Pinot Gris,13
103321,big rich powered intense spiciness rounded tex...,21.0,Domaine Schoffit,Gewürztraminer,7

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer

vect = TfidfVectorizer(analyzer='word',stop_words= 'english',max_features=5000)
new_df = vect.fit_transform(df_trail['review_description'])
new_df

<96359x5000 sparse matrix of type '<class 'numpy.float64'>'
	with 2052457 stored elements in Compressed Sparse Row format>

In [38]:
df_desc= new_df.toarray()
len(df_desc)

MemoryError: Unable to allocate 3.59 GiB for an array with shape (96359, 5000) and data type float64

In [ ]:
df_used=pd.DataFrame(df_desc)
df_used[5000]=df_trail['price']
df_used

In [ ]:
df_used1 = df_used.dropna()
df_used1[5000].isna().sum()

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df_used, df_trail['variety_encoded'], test_size=0.2, random_state=0)

In [ ]:
X_train.head(10)

In [ ]:
# from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
# dt = DecisionTreeClassifier()
rf = RandomForestClassifier(n_estimators=75,random_state=42)
rf.fit(X_train, y_train)